swagger: "2.0"
info:
  description: "This is a sample User Api"
  version: "1.0.0"
  title: "Assessment"
basePath: ""
host: "localhost:8080"
tags:
  - name: "Users"
    description: "get data about the registered users"
schemes:
  - "http"
paths:
  /users:
    get:
      tags:
        - "Users"
      summary: "Returns all the registered users"
      description: ""
      operationId: "getUsers"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "gender"
          description: "User Gender"
          required: false
          type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      status:
        type: "string"